### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by arvl130** [arvl130/nuxt-lfi-dental-clinic#1]
- [x] Add asterisks to Admin Edit Password (eddie)
- [x] Make modals use rounded corners (eddie)
- [x] Add archived messages to Admin Messages page (me)
- [x] Fix: results not showing in Dental Treatments page (me)
- [x] Use `<select>` element in Medical Chart gender. (me)
- [x] Use single Login page. (me)
- [x] Hide Update button when no Profile Picture is selected. (me)
- [x] Implement new Calendar designs. (me)
- [x] Set consistent height for Patient Record entries. (eddie)
- [x] Change My Account banner blur to 2.5px, instead of blur-sm. (eddie)
- [x] Load only up to 8 Patient Records w/ search. (me)
- [x] Patients should not have to repeat typing their name when registering. (me)
- [x] Move backend to Vercel for more 🚴💨 (me)
- [x] Add archive view in Patient Records. (me)
- [x] Use single footer for all pages (Admin and Patient). (mike)
- [x] Add mobile navbar to pages using Admin BaseLayout. (mike)
- [x] Implement new Footer design. (mike)
- [x] Show createdAt date when opening message. (mike)
- [x] Add email verification. (me)
- [x] Password reset flow. (me)
- [x] Responsive Admin Messages page (me)
- [x] Admin message field should be "email" not "subject" (me)
- [x] Make email field in Admin messages a mailto: link  (me)
- [x] Prevent double clicking in account login (me)
- [x] Notify patients the night before appointment. (me)
- [x] Status -> Attended / Paid, esp. on mobile pages. (me)
- [x] Automatically calculate balance for each dental treatment. (me)
- [x] Update email template. (me)
- [x] Limit possible appointment dates. (me)
- [x] Fix links in the footer. (me)
- [x] Add loading skeleton. (me)

**Comment by arvl130** [comment]
Closing because all tasks have been ticked.
